export const PATHS = {
  HOME: "/",
  ABOUT: "/about",
  SHOP: "/shop",
  PRODUCT: (slug: string) => `/shop/${slug}`,
  PRODUCT_PATTERN: "/shop/:slug",
  BLOG: "/blog",
  BLOG_POST: (slug: string) => `/blog/${slug}`,
  BLOG_POST_PATTERN: "/blog/:slug",
  CONTACT: "/contact",
  CART: "/cart",
  LOGIN: "/login",
  SIGNUP: "/signup",
  PROFILE: "/profile",
  PROFILE_EDIT: "/profile/edit",
  PROFILE_ORDERS: "/profile/orders",
  CHECKOUT: "/checkout",
  ORDER_SUCCESS: (orderId: string) => `/order/success/${orderId}`,
  ORDER_SUCCESS_PATTERN: "/order/success/:orderId",

  ADMIN: "/admin",
  ADMIN_PRODUCTS: "/admin/products",
  ADMIN_PRODUCT_NEW: "/admin/products/new",
  ADMIN_PRODUCT_EDIT: (id: string) => `/admin/products/${id}/edit`,
  ADMIN_PRODUCT_EDIT_PATTERN: "/admin/products/:id/edit",
  ADMIN_ORDERS: "/admin/orders",
  ADMIN_ORDER_DETAIL: (id: string) => `/admin/orders/${id}`,
  ADMIN_ORDER_DETAIL_PATTERN: "/admin/orders/:id",
  ADMIN_BLOG: "/admin/blog",
  ADMIN_BLOG_NEW: "/admin/blog/new",
  ADMIN_BLOG_EDIT: (id: string) => `/admin/blog/${id}/edit`,
  ADMIN_BLOG_EDIT_PATTERN: "/admin/blog/:id/edit",
} as const;
